services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none

  backend-dev:
    depends_on:
      - mongo
    container_name: dev_excuse_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /backend
          action: sync
          ignore:
            - node_modules/

  frontend-dev:
    depends_on:
      - backend-dev
    container_name: dev_excuse_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /frontend
          action: sync
          ignore:
            - node_modules/

  backend-prod:
    depends_on:
      - mongo
    container_name: prod_excuse_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 3001:3001

  frontend-prod:
    depends_on:
      - backend-prod
    container_name: prod_excuse_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 4173:4173

volumes:
  mongo-data:
